In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/raw/acs_16_ntx_counties.csv') #read in 2016 data

cols = df.columns #create list of column names

cols = [col.lower().replace(' ', '_') for col in cols] #convert columns to snake case
cols = [col.lower().replace('(', '').replace(')', '') for col in cols] #strip parentheses

for i,j in enumerate(cols): #remove Census prefixes 
    if '!!' in j:
        cols[i] = j.split('!!')[-1]
    else:
        pass

df.columns = cols #rename columns to cleaned values
df['label_grouping'] = df['label_grouping'].str.replace(' -> ', '')
county = '' #create temp variable to hold county name
for i,j in enumerate(df['label_grouping']):
    if ' County, Texas' in j: #data is not structured correctly, so we need to clean it up
        county = j.split(' ')[0] #grab just the county name
    else:
        df['label_grouping'][i] = county.strip() + '_' + j.strip() #add county name to the front of the label

df['label_grouping'] = df['label_grouping'].str.replace(' County, Texas', '') #clean up label grouping column
df['label_grouping'] = df['label_grouping'].str.replace('_  ', '_')

df = df.dropna(subset=['total_population']).reset_index(drop=True) #drop nan rows
df = df.dropna(axis=1).reset_index(drop=True) #drop nan columns
df['year'] = 2016 #add year column

df.to_csv('data/cleaned/acs_16_ntx_counties_cleaned.csv', index=False) #save cleaned data
df

/var/folders/kd/czy8636s60z_vkm36s066th80000gq/T/ipykernel_14231/985369621.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label_grouping'][i] = county.strip() + '_' + j.strip() #add county name to the front of the label

,label_grouping,total_population,male,female,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,25_to_34_years,...,native_hawaiian_and_other_pacific_islander_alone,some_other_race_alone,two_or_more_races,two_races_including_some_other_race,"two_races_excluding_some_other_race,_and_three_or_more_races",total_housing_units,"citizen,_18_and_over_population",male,female,year
0,Collin_Estimate,"939,585","461,416","478,169","59,881","70,278","75,119","67,842","53,107","118,559",...,822,"2,793","24,250","1,106","23,144","351,310","606,908","291,829","315,079",2016
1,Collin_Percent,"939,585",49.1%,50.9%,6.4%,7.5%,8.0%,7.2%,5.7%,12.6%,...,0.1%,0.3%,2.6%,0.1%,2.5%,(X),"606,908",48.1%,51.9%,2016
2,Dallas_Estimate,"2,574,984","1,267,526","1,307,458","196,093","200,043","182,154","174,048","184,076","415,787",...,"1,103","5,495","43,902","2,650","41,252","1,003,060","1,477,187","700,368","776,819",2016
3,Dallas_Percent,"2,574,984",49.2%,50.8%,7.6%,7.8%,7.1%,6.8%,7.1%,16.1%,...,0.0%,0.2%,1.7%,0.1%,1.6%,(X),"1,477,187",47.4%,52.6%,2016
4,Denton_Estimate,"806,180","396,322","409,858","52,575","59,296","58,398","58,175","53,497","119,677",...,559,"1,824","25,759",779,"24,980","297,936","544,590","263,665","280,925",2016
5,Denton_Percent,"806,180",49.2%,50.8%,6.5%,7.4%,7.2%,7.2%,6.6%,14.8%,...,0.1%,0.2%,3.2%,0.1%,3.1%,(X),"544,590",48.4%,51.6%,2016
6,Ellis_Estimate,"168,499","83,163","85,336","11,449","12,162","13,373","13,027","10,855","21,414",...,83,167,"3,139",0,"3,139","59,393","114,669","55,142","59,527",2016
7,Ellis_Percent,"168,499",49.4%,50.6%,6.8%,7.2%,7.9%,7.7%,6.4%,12.7%,...,0.0%,0.1%,1.9%,0.0%,1.9%,(X),"114,669",48.1%,51.9%,2016
8,Kaufman_Estimate,"118,350","58,708","59,642","8,360","8,339","9,996","8,352","7,085","15,925",...,0,277,"1,532",0,"1,532","40,082","79,532","38,140","41,392",2016
9,Kaufman_Percent,"118,350",49.6%,50.4%,7.1%,7.0%,8.4%,7.1%,6.0%,13.5%,...,0.0%,0.2%,1.3%,0.0%,1.3%,(X),"79,532",48.0%,52.0%,2016
10,Rockwall_Estimate,"93,978","45,729","48,249","4,954","6,723","9,039","7,969","5,280","9,289",...,0,0,"1,734",0,"1,734","32,700","63,224","30,656","32,568",2016
11,Rockwall_Percent,"93,978",48.7%,51.3%,5.3%,7.2%,9.6%,8.5%,5.6%,9.9%,...,0.0%,0.0%,1.8%,0.0%,1.8%,(X),"63,224",48.5%,51.5%,2016
12,Tarrant_Estimate,"2,016,872","985,977","1,030,895","145,627","150,345","154,051","142,314","135,933","300,187",...,"2,648","2,931","48,012","1,212","46,800","756,596","1,293,167","618,188","674,979",2016
13,Tarrant_Percent,"2,016,872",48.9%,51.1%,7.2%,7.5%,7.6%,7.1%,6.7%,14.9%,...,0.1%,0.1%,2.4%,0.1%,2.3%,(X),"1,293,167",47.8%,52.2%,2016

In [3]:
df1 = pd.read_csv('data/raw/acs_21_ntx_counties.csv')
cols = df1.columns

cols = [col.lower().replace(' ', '_') for col in cols]
cols = [col.lower().replace('(', '').replace(')', '') for col in cols]
for i,j in enumerate(cols):
    if '!!' in j:
        cols[i] = j.split('!!')[-1]
    else:
        pass
df1.columns = cols
county = ''
for i,j in enumerate(df1['label_grouping']):
    if ' County, Texas' in j:
        county = j.split(' ')[0]
    else:
        df1['label_grouping'][i] = county.strip() + '_' + j.strip()

df1['label_grouping'] = df1['label_grouping'].str.replace(' County, Texas', '')
df1['label_grouping'] = df1['label_grouping'].str.replace('_  ', '_')

df1 = df1.dropna(subset=['total_population']).reset_index(drop=True)
df1 = df1.dropna(axis=1).reset_index(drop=True)
df1['year'] = 2021

df1.to_csv('data/cleaned/acs_21_ntx_counties_cleaned.csv', index=False)
df1

/var/folders/kd/czy8636s60z_vkm36s066th80000gq/T/ipykernel_14231/1915029573.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['label_grouping'][i] = county.strip() + '_' + j.strip()

,label_grouping,total_population,male,female,sex_ratio_males_per_100_females,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,...,native_hawaiian_and_other_pacific_islander_alone,some_other_race_alone,two_or_more_races,two_races_including_some_other_race,"two_races_excluding_some_other_race,_and_three_or_more_races",total_housing_units,"citizen,_18_and_over_population",male,female,year
0,Collin_Estimate,"1,039,812","515,290","524,522",98.2,"62,594","74,754","81,749","75,576","59,435",...,552,"5,182","34,850","5,255","29,595","392,627","665,596","323,662","341,934",2021
1,Collin_Percent,"1,039,812",49.6%,50.4%,(X),6.0%,7.2%,7.9%,7.3%,5.7%,...,0.1%,0.5%,3.4%,0.5%,2.8%,(X),"665,596",48.6%,51.4%,2021
2,Dallas_Estimate,"2,604,722","1,290,636","1,314,086",98.2,"187,909","183,336","197,255","179,530","178,937",...,772,"6,481","55,740","5,083","50,657","1,028,817","1,526,728","735,354","791,374",2021
3,Dallas_Percent,"2,604,722",49.5%,50.5%,(X),7.2%,7.0%,7.6%,6.9%,6.9%,...,0.0%,0.2%,2.1%,0.2%,1.9%,(X),"1,526,728",48.2%,51.8%,2021
4,Denton_Estimate,"885,012","437,308","447,704",97.7,"53,454","60,556","63,565","63,419","56,827",...,723,"1,972","30,038","3,683","26,355","339,202","602,220","292,195","310,025",2021
5,Denton_Percent,"885,012",49.4%,50.6%,(X),6.0%,6.8%,7.2%,7.2%,6.4%,...,0.1%,0.2%,3.4%,0.4%,3.0%,(X),"602,220",48.5%,51.5%,2021
6,Ellis_Estimate,"187,984","93,269","94,715",98.5,"12,270","13,147","15,780","14,125","11,312",...,37,356,"4,847",552,"4,295","66,793","129,644","62,632","67,012",2021
7,Ellis_Percent,"187,984",49.6%,50.4%,(X),6.5%,7.0%,8.4%,7.5%,6.0%,...,0.0%,0.2%,2.6%,0.3%,2.3%,(X),"129,644",48.3%,51.7%,2021
8,Kaufman_Estimate,"140,145","69,372","70,773",98.0,"9,945","11,285","11,312","10,522","7,770",...,83,81,"3,543",352,"3,191","49,393","94,567","46,180","48,387",2021
9,Kaufman_Percent,"140,145",49.5%,50.5%,(X),7.1%,8.1%,8.1%,7.5%,5.5%,...,0.1%,0.1%,2.5%,0.3%,2.3%,(X),"94,567",48.8%,51.2%,2021
10,Rockwall_Estimate,"105,227","52,295","52,932",98.8,"6,407","8,003","8,616","8,105","5,475",...,50,387,"2,334",158,"2,176","37,221","72,733","35,615","37,118",2021
11,Rockwall_Percent,"105,227",49.7%,50.3%,(X),6.1%,7.6%,8.2%,7.7%,5.2%,...,0.0%,0.4%,2.2%,0.2%,2.1%,(X),"72,733",49.0%,51.0%,2021
12,Tarrant_Estimate,"2,091,953","1,027,266","1,064,687",96.5,"141,259","150,938","162,240","152,951","137,822",...,"3,796","6,829","57,792","4,063","53,729","797,482","1,362,116","656,531","705,585",2021
13,Tarrant_Percent,"2,091,953",49.1%,50.9%,(X),6.8%,7.2%,7.8%,7.3%,6.6%,...,0.2%,0.3%,2.8%,0.2%,2.6%,(X),"1,362,116",48.2%,51.8%,2021

In [4]:
df = df.loc[:,~df.columns.duplicated()].copy() #remove duplicate columns
df1 = df1.loc[:,~df1.columns.duplicated()].copy()
df = pd.concat([df, df1]).reset_index(drop=True) #concatenate dataframes

In [5]:
for i in df.columns: #remove commas and percent signs from string columns
    if type(df[i][0]) == str: 
        df[i] = df[i].str.replace(',', '')
        df[i] = df[i].str.replace('%', '')
    else:
        pass
cols = list(df.columns)
cols = [i for i in cols if i != 'label_grouping']
cols
for i in cols: #convert number columns to floats
    df[i] = pd.to_numeric(df[i], errors='coerce')
df

,label_grouping,total_population,male,female,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,25_to_34_years,...,"two_races_excluding_some_other_race,_and_three_or_more_races",total_housing_units,"citizen,_18_and_over_population",year,sex_ratio_males_per_100_females,under_18_years,16_years_and_over,one_race.1,chamorro,two_or_more_races.1
0,Collin_Estimate,939585,461416.0,478169.0,59881.0,70278.0,75119.0,67842.0,53107.0,118559.0,...,23144.0,351310.0,606908,2016,NaN,NaN,NaN,NaN,NaN,NaN
1,Collin_Percent,939585,49.1,50.9,6.4,7.5,8.0,7.2,5.7,12.6,...,2.5,NaN,606908,2016,NaN,NaN,NaN,NaN,NaN,NaN
2,Dallas_Estimate,2574984,1267526.0,1307458.0,196093.0,200043.0,182154.0,174048.0,184076.0,415787.0,...,41252.0,1003060.0,1477187,2016,NaN,NaN,NaN,NaN,NaN,NaN
3,Dallas_Percent,2574984,49.2,50.8,7.6,7.8,7.1,6.8,7.1,16.1,...,1.6,NaN,1477187,2016,NaN,NaN,NaN,NaN,NaN,NaN
4,Denton_Estimate,806180,396322.0,409858.0,52575.0,59296.0,58398.0,58175.0,53497.0,119677.0,...,24980.0,297936.0,544590,2016,NaN,NaN,NaN,NaN,NaN,NaN
5,Denton_Percent,806180,49.2,50.8,6.5,7.4,7.2,7.2,6.6,14.8,...,3.1,NaN,544590,2016,NaN,NaN,NaN,NaN,NaN,NaN
6,Ellis_Estimate,168499,83163.0,85336.0,11449.0,12162.0,13373.0,13027.0,10855.0,21414.0,...,3139.0,59393.0,114669,2016,NaN,NaN,NaN,NaN,NaN,NaN
7,Ellis_Percent,168499,49.4,50.6,6.8,7.2,7.9,7.7,6.4,12.7,...,1.9,NaN,114669,2016,NaN,NaN,NaN,NaN,NaN,NaN
8,Kaufman_Estimate,118350,58708.0,59642.0,8360.0,8339.0,9996.0,8352.0,7085.0,15925.0,...,1532.0,40082.0,79532,2016,NaN,NaN,NaN,NaN,NaN,NaN
9,Kaufman_Percent,118350,49.6,50.4,7.1,7.0,8.4,7.1,6.0,13.5,...,1.3,NaN,79532,2016,NaN,NaN,NaN,NaN,NaN,NaN
10,Rockwall_Estimate,93978,45729.0,48249.0,4954.0,6723.0,9039.0,7969.0,5280.0,9289.0,...,1734.0,32700.0,63224,2016,NaN,NaN,NaN,NaN,NaN,NaN
11,Rockwall_Percent,93978,48.7,51.3,5.3,7.2,9.6,8.5,5.6,9.9,...,1.8,NaN,63224,2016,NaN,NaN,NaN,NaN,NaN,NaN
12,Tarrant_Estimate,2016872,985977.0,1030895.0,145627.0,150345.0,154051.0,142314.0,135933.0,300187.0,...,46800.0,756596.0,1293167,2016,NaN,NaN,NaN,NaN,NaN,NaN
13,Tarrant_Percent,2016872,48.9,51.1,7.2,7.5,7.6,7.1,6.7,14.9,...,2.3,NaN,1293167,2016,NaN,NaN,NaN,NaN,NaN,NaN
14,Collin_Estimate,1039812,515290.0,524522.0,62594.0,74754.0,81749.0,75576.0,59435.0,131818.0,...,29595.0,392627.0,665596,2021,98.2,NaN,NaN,NaN,151.0,NaN
15,Collin_Percent,1039812,49.6,50.4,6.0,7.2,7.9,7.3,5.7,12.7,...,2.8,NaN,665596,2021,NaN,NaN,NaN,NaN,NaN,NaN
16,Dallas_Estimate,2604722,1290636.0,1314086.0,187909.0,183336.0,197255.0,179530.0,178937.0,426166.0,...,50657.0,1028817.0,1526728,2021,98.2,NaN,NaN,NaN,217.0,NaN
17,Dallas_Percent,2604722,49.5,50.5,7.2,7.0,7.6,6.9,6.9,16.4,...,1.9,NaN,1526728,2021,NaN,NaN,NaN,NaN,NaN,NaN
18,Denton_Estimate,885012,437308.0,447704.0,53454.0,60556.0,63565.0,63419.0,56827.0,128683.0,...,26355.0,339202.0,602220,2021,97.7,NaN,NaN,NaN,145.0,NaN
19,Denton_Percent,885012,49.4,50.6,6.0,6.8,7.2,7.2,6.4,14.5,...,3.0,NaN,602220,2021,NaN,NaN,NaN,NaN,NaN,NaN
20,Ellis_Estimate,187984,93269.0,94715.0,12270.0,13147.0,15780.0,14125.0,11312.0,24068.0,...,4295.0,66793.0,129644,2021,98.5,NaN,NaN,NaN,0.0,NaN
21,Ellis_Percent,187984,49.6,50.4,6.5,7.0,8.4,7.5,6.0,12.8,...,2.3,NaN,129644,2021,NaN,NaN,NaN,NaN,NaN,NaN
22,Kaufman_Estimate,140145,69372.0,70773.0,9945.0,11285.0,11312.0,10522.0,7770.0,19113.0,...,3191.0,49393.0,94567,2021,98.0,NaN,NaN,NaN,76.0,NaN
23,Kaufman_Percent,140145,49.5,50.5,7.1,8.1,8.1,7.5,5.5,13.6,...,2.3,NaN,94567,2021,NaN,NaN,NaN,NaN,NaN,NaN
24,Rockwall_Estimate,105227,52295.0,52932.0,6407.0,8003.0,8616.0,8105.0,5475.0,11990.0,...,2176.0,37221.0,72733,2021,98.8,NaN,NaN,NaN,0.0,NaN
25,Rockwall_Percent,105227,49.7,50.3,6.1,7.6,8.2,7.7,5.2,11.4,...,2.1,NaN,72733,2021,NaN,NaN,NaN,NaN,NaN,NaN
26,Tarrant_Estimate,2091953,1027266.0,1064687.0,141259.0,150938.0,162240.0,152951.0,137822.0,308580.0,...,53729.0,797482.0,1362116,2021,96.5,NaN,NaN,NaN,853.0,NaN
27,Tarrant_Percent,2091953,49.1,50.9,6.8,7.2,7.8,7.3,6.6,14.8,...,2.6,NaN,1362116,2021,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.loc[df['label_grouping'].str.contains('Estimate')].reset_index(drop=True)
df = df[['label_grouping', 'year', 'total_population', 'male', 'female', 'median_age_years', '18_years_and_over', 'white', 'black_or_african_american', 'asian', 'two_or_more_races', 'hispanic_or_latino_of_any_race', 'total_housing_units', 'american_indian_and_alaska_native']]
df['children'] = df['total_population'] - df['18_years_and_over']
df = df.sort_values(by=['label_grouping', 'year']).reset_index(drop=True)
df

,label_grouping,year,total_population,male,female,median_age_years,18_years_and_over,white,black_or_african_american,asian,two_or_more_races,hispanic_or_latino_of_any_race,total_housing_units,american_indian_and_alaska_native,children
0,Collin_Estimate,2016,939585,461416.0,478169.0,36.5,689140.0,661559.0,87766.0,132486.0,30294.0,142209.0,351310.0,3583.0,250445.0
1,Collin_Estimate,2021,1039812,515290.0,524522.0,37.2,770914.0,653729.0,105044.0,169344.0,75087.0,161908.0,392627.0,4649.0,268898.0
2,Dallas_Estimate,2016,2574984,1267526.0,1307458.0,33.3,1887641.0,1591187.0,582365.0,157592.0,76321.0,1026256.0,1003060.0,6506.0,687343.0
3,Dallas_Estimate,2021,2604722,1290636.0,1314086.0,33.7,1924278.0,1348117.0,586142.0,171844.0,254262.0,1060847.0,1028817.0,14247.0,680444.0
4,Denton_Estimate,2016,806180,396322.0,409858.0,35.1,600568.0,599270.0,74199.0,63864.0,32224.0,154800.0,297936.0,3992.0,205612.0
5,Denton_Estimate,2021,885012,437308.0,447704.0,36.2,668327.0,603389.0,90834.0,83987.0,73598.0,173708.0,339202.0,4616.0,216685.0
6,Ellis_Estimate,2016,168499,83163.0,85336.0,36.1,123407.0,141134.0,16525.0,1390.0,5884.0,43587.0,59393.0,1104.0,45092.0
7,Ellis_Estimate,2021,187984,93269.0,94715.0,36.4,137683.0,138798.0,21196.0,1371.0,15418.0,51109.0,66793.0,1110.0,50301.0
8,Kaufman_Estimate,2016,118350,58708.0,59642.0,36.0,85946.0,98799.0,12733.0,1429.0,2213.0,24205.0,40082.0,324.0,32404.0
9,Kaufman_Estimate,2021,140145,69372.0,70773.0,35.0,100645.0,100433.0,19113.0,1889.0,13258.0,33145.0,49393.0,450.0,39500.0
10,Rockwall_Estimate,2016,93978,45729.0,48249.0,37.5,68270.0,80801.0,5936.0,2560.0,3058.0,16097.0,32700.0,54.0,25708.0
11,Rockwall_Estimate,2021,105227,52295.0,52932.0,37.6,76772.0,81467.0,7606.0,3260.0,7891.0,19813.0,37221.0,936.0,28455.0
12,Tarrant_Estimate,2016,2016872,985977.0,1030895.0,34.3,1477573.0,1367728.0,320375.0,109096.0,66217.0,573205.0,756596.0,9482.0,539299.0
13,Tarrant_Estimate,2021,2091953,1027266.0,1064687.0,34.8,1542027.0,1245396.0,354778.0,118506.0,179633.0,617233.0,797482.0,10290.0,549926.0

## Percent Change

In [7]:
ds = [] #create list to store dictionaries
cols = list(df.columns) #create list of column names

for i in list(df['label_grouping'].unique()): #loop through each county
    d = {} #create dictionary
    d['county'] = i #add county name to dictionary
    for j in cols: #loop through each numeric column
        if j not in ['label_grouping', 'year']: #skip non-numeric columns
            try: #calculate percent change
                d[j] =  ((float(df.loc[((df['label_grouping'] == i) & (df['year'] == 2021)),  j])) - float(df.loc[((df['label_grouping'] == i) & (df['year'] == 2016)),  j]))  / float(df.loc[((df['label_grouping'] == i) & (df['year'] == 2016)),  j]) * 100
            except ZeroDivisionError: #if one of the values is zero, set percent change to zero
                d[j] = 0
        else:
            pass
    
    ds.append(d) #add dictionary to list
dfx = pd.DataFrame(ds) #create dataframe from list of dictionaries
cols = ['change_' + i for i in cols] #add change_ prefix to column names
cols = ['county'] + cols #rename columns
cols.remove('change_label_grouping') #remove label_grouping column
cols.remove('change_year') #remove year column
dfx.columns = cols
dfx
dfx.to_csv('data/created/acs_16_21_percent_change.csv', index=False) #save dataframe to csv

,county,change_total_population,change_male,change_female,change_median_age_years,change_18_years_and_over,change_white,change_black_or_african_american,change_asian,change_two_or_more_races,change_hispanic_or_latino_of_any_race,change_total_housing_units,change_american_indian_and_alaska_native,change_children
0,Collin_Estimate,10.667156,11.675798,9.693853,1.917808,11.866094,-1.183568,19.686439,27.820298,147.860963,13.852147,11.760838,29.751605,7.368085
1,Dallas_Estimate,1.154881,1.823237,0.506938,1.201201,1.940888,-15.276017,0.648562,9.043606,233.148151,3.370601,2.567842,118.982478,-1.003720
2,Denton_Estimate,9.778461,10.341591,9.233930,3.133903,11.282486,0.687336,22.419440,31.509144,128.394985,12.214470,13.850626,15.631263,5.385386
3,Ellis_Estimate,11.563867,12.152039,10.990672,0.831025,11.568225,-1.655165,28.266263,-1.366906,162.032631,17.257439,12.459381,0.543478,11.551938
4,Kaufman_Estimate,18.415716,18.164475,18.663023,-2.777778,17.102599,1.653863,50.106024,32.190343,499.096249,36.934518,23.229879,38.888889,21.898531
5,Rockwall_Estimate,11.969823,14.358503,9.705901,0.266667,12.453493,0.824247,28.133423,27.343750,158.044474,23.085047,13.825688,1633.333333,10.685390
6,Tarrant_Estimate,3.722646,4.187623,3.277928,1.457726,4.362153,-8.944176,10.738353,8.625431,171.279279,7.681022,5.403941,8.521409,1.970521

In [8]:
ds = [] #create list to store dictionaries
cols = list(df.columns) #create list of column names

for i in list(df['label_grouping'].unique()): #loop through each county
    d = {} #create dictionary
    d['county'] = i #add county name to dictionary
    for j in cols: #loop through each numeric column
        if j not in ['label_grouping', 'year']: #skip non-numeric columns
            try: #calculate percent change
                d[j] =  ((float(df.loc[((df['label_grouping'] == i) & (df['year'] == 2021)),  j])) - float(df.loc[((df['label_grouping'] == i) & (df['year'] == 2016)),  j]))
            except ZeroDivisionError: #if one of the values is zero, set percent change to zero
                d[j] = 0
        else:
            pass
    
    ds.append(d) #add dictionary to list
dfx = pd.DataFrame(ds) #create dataframe from list of dictionaries
cols = ['difference_' + i for i in cols] #add change_ prefix to column names
cols = ['county'] + cols #rename columns
cols.remove('difference_label_grouping') #remove label_grouping column
cols.remove('difference_year') #remove year column
dfx.columns = cols
dfx

,county,difference_total_population,difference_male,difference_female,difference_median_age_years,difference_18_years_and_over,difference_white,difference_black_or_african_american,difference_asian,difference_two_or_more_races,difference_hispanic_or_latino_of_any_race,difference_total_housing_units,difference_american_indian_and_alaska_native,difference_children
0,Collin_Estimate,100227.0,53874.0,46353.0,0.7,81774.0,-7830.0,17278.0,36858.0,44793.0,19699.0,41317.0,1066.0,18453.0
1,Dallas_Estimate,29738.0,23110.0,6628.0,0.4,36637.0,-243070.0,3777.0,14252.0,177941.0,34591.0,25757.0,7741.0,-6899.0
2,Denton_Estimate,78832.0,40986.0,37846.0,1.1,67759.0,4119.0,16635.0,20123.0,41374.0,18908.0,41266.0,624.0,11073.0
3,Ellis_Estimate,19485.0,10106.0,9379.0,0.3,14276.0,-2336.0,4671.0,-19.0,9534.0,7522.0,7400.0,6.0,5209.0
4,Kaufman_Estimate,21795.0,10664.0,11131.0,-1.0,14699.0,1634.0,6380.0,460.0,11045.0,8940.0,9311.0,126.0,7096.0
5,Rockwall_Estimate,11249.0,6566.0,4683.0,0.1,8502.0,666.0,1670.0,700.0,4833.0,3716.0,4521.0,882.0,2747.0
6,Tarrant_Estimate,75081.0,41289.0,33792.0,0.5,64454.0,-122332.0,34403.0,9410.0,113416.0,44028.0,40886.0,808.0,10627.0

In [9]:
df['non_white_proportion'] = 100 - (df['white'] / df['total_population'] * 100)
df

,label_grouping,year,total_population,male,female,median_age_years,18_years_and_over,white,black_or_african_american,asian,two_or_more_races,hispanic_or_latino_of_any_race,total_housing_units,american_indian_and_alaska_native,children,non_white_proportion
0,Collin_Estimate,2016,939585,461416.0,478169.0,36.5,689140.0,661559.0,87766.0,132486.0,30294.0,142209.0,351310.0,3583.0,250445.0,29.590298
1,Collin_Estimate,2021,1039812,515290.0,524522.0,37.2,770914.0,653729.0,105044.0,169344.0,75087.0,161908.0,392627.0,4649.0,268898.0,37.130077
2,Dallas_Estimate,2016,2574984,1267526.0,1307458.0,33.3,1887641.0,1591187.0,582365.0,157592.0,76321.0,1026256.0,1003060.0,6506.0,687343.0,38.205946
3,Dallas_Estimate,2021,2604722,1290636.0,1314086.0,33.7,1924278.0,1348117.0,586142.0,171844.0,254262.0,1060847.0,1028817.0,14247.0,680444.0,48.243344
4,Denton_Estimate,2016,806180,396322.0,409858.0,35.1,600568.0,599270.0,74199.0,63864.0,32224.0,154800.0,297936.0,3992.0,205612.0,25.665484
5,Denton_Estimate,2021,885012,437308.0,447704.0,36.2,668327.0,603389.0,90834.0,83987.0,73598.0,173708.0,339202.0,4616.0,216685.0,31.821376
6,Ellis_Estimate,2016,168499,83163.0,85336.0,36.1,123407.0,141134.0,16525.0,1390.0,5884.0,43587.0,59393.0,1104.0,45092.0,16.240452
7,Ellis_Estimate,2021,187984,93269.0,94715.0,36.4,137683.0,138798.0,21196.0,1371.0,15418.0,51109.0,66793.0,1110.0,50301.0,26.164993
8,Kaufman_Estimate,2016,118350,58708.0,59642.0,36.0,85946.0,98799.0,12733.0,1429.0,2213.0,24205.0,40082.0,324.0,32404.0,16.519645
9,Kaufman_Estimate,2021,140145,69372.0,70773.0,35.0,100645.0,100433.0,19113.0,1889.0,13258.0,33145.0,49393.0,450.0,39500.0,28.336366
10,Rockwall_Estimate,2016,93978,45729.0,48249.0,37.5,68270.0,80801.0,5936.0,2560.0,3058.0,16097.0,32700.0,54.0,25708.0,14.021367
11,Rockwall_Estimate,2021,105227,52295.0,52932.0,37.6,76772.0,81467.0,7606.0,3260.0,7891.0,19813.0,37221.0,936.0,28455.0,22.579756
12,Tarrant_Estimate,2016,2016872,985977.0,1030895.0,34.3,1477573.0,1367728.0,320375.0,109096.0,66217.0,573205.0,756596.0,9482.0,539299.0,32.185682
13,Tarrant_Estimate,2021,2091953,1027266.0,1064687.0,34.8,1542027.0,1245396.0,354778.0,118506.0,179633.0,617233.0,797482.0,10290.0,549926.0,40.467305